name: Security Audit

on:
  push:
    paths: 
      - 'vendor/**'
  pull_request:
    paths: 
      - 'vendor/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run security-audit
        uses: golang/govulncheck-action@v1